#List Program
list=[10,20,30,40,50,60,70,80,90,100]
print(list)
print("Inserting (with index):")
list.insert(3,33)
print(list)
print("Appending (at last):")
list.append(20)
print(list)
print("Removing (only element)")
list.remove(20)
print(list)
print("Length of the list:",len(list))
list.clear()
print("Clearing list:")
print(list)